version: '3.9'

networks:
  challenge-network:
    driver: bridge
    name: challenge-network

services:
  db:
    container_name: meli-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postuser
      - POSTGRES_PASSWORD=postpass
      - POSTGRES_DB=meli
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - challenge-network
    healthcheck:
      test:  ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  userapi:
    container_name: meli-user-api
    build:
      context: .
      dockerfile: Dockerfile-user
    ports:
      - "8080:8080"
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_healthy
  
  notifyapi:
    container_name: meli-notify-api
    build:
      context: .
      dockerfile: Dockerfile-notify
    ports:
      - "8081:8081"
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_healthy


